--- 
title: "rlang Book Club"
author: "The R4DS Online Learning Community"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
github-repo: r4ds/bookclub-rlang
description: "This website is the product of the R4DS Online Learning Community's rlang Book Club."
---

# Welcome {-}

Welcome to the rlang book club! 

This website is a companion for the [{rlang} package documentation](https://rlang.r-lib.org/) by Lionel Henry & Hadley Wickham.

-   These are **shared slides!**
    -   Developed by the [R4DS Online Learning Community](https://rfordatasci.com).
    -   [Join the community](https://r4ds.io/join) to participate.
    -   Available at [r4ds.io/rlang](https://r4ds.io/rlang).
-   We follow the [R4DS Online Learning Community Code of Conduct](https://r4ds.io/conduct).

## Pace {-}

-   Meet **every week.**
    -   Try to **always meet** even if presenter can't.
    -   I might skip July 7 if we're still going.
    -   Let me know if there's a holiday, etc.
-   **Ambitious pace** on schedule.
    -   Amount of text is **roughly** equivalent to a chapter.
-   Split content if you need to!

## Format {-}

-   [**Volunteer to lead discussion!**](https://docs.google.com/spreadsheets/d/1Rw6TXuC0xP43JpzjCpYS70do04OEyaj6XjyKiOkXy90/edit?usp=sharing)
    -   **This is the best way to learn the material!**
-   Ideally **update shared slides**.
    -   Instructions in [github repo](https://github.com/r4ds/bookclub-rlang).
    -   **Embedded code** is almost always easier to follow than live demos!
-   Presentations **recorded** & available on [**R4DS Online Learning Community YouTube Channel**](https://r4ds.io/youtube).
